# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  awsRegion: 'us-east-1'
  ecrRepositoryName: 'frontend-airties-1'
  containerName: 'airties-frontend-app'
  ecsClusterName: 'frontend-airties-1'
  ecsServiceName: 'airties-ecs-service'
  dockerImageTag: 'latest'
  awsAccessKeyId: $(AWS-ACCESS-KEY)
  awsSecretAccessKey: $(AWS-SECRET-KEY)
  awsSessionToken: $(AWS-TOKEN)

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'AWS'
              repository: '$(ecrRepositoryName)'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              tags: $(dockerImageTag)
  
  - stage:
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - script: |
             aws ecs update-service --cluster $(ecsClusterName) --service $(ecsServiceName) --force-new-deployment
            displayName: 'Deploy to ECS'
            env:
              AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
              AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)
              AWS_SESSION_TOKEN: $(awsSessionToken) 

